---
title: "2018 Leaf Scan Analysis"
output: html_notebook
---

Date initiated: 2019-05-06
Date compiled: `r Sys.Date()`
```{r}
library(here)
library(tidyverse)
library(glue)
```

# Choose random images for training set

First, copy a random subset of files to use as a training set.

```{r}
scandir <- "/Users/scottericr/Box/Image Analysis/2018/Leaf Scans/Manipulative"
leaves <- list.files(scandir, recursive = TRUE, pattern = "leaf.+\\.png", full.names = FALSE)
length(leaves)

# runif(1, 1, 1000)
set.seed(688)
test <- sample(leaves, 40)

str_view(test, "[^/]+(?=.png)")

df <- tibble(path = leaves)
df <- df %>%
  mutate(cultivar = str_extract(path, "^[^/]+(?=/)"),
         scan = str_extract(path, "(?<=/).+(?=/)"),
         leaf = str_extract(path, "[^/]+(?=.png)")) %>% 
  mutate(new.filename = glue("{scan}_{leaf}.png"),
         from.path = glue("{scandir}/{path}"),
         to.path = glue("{scandir}/Training Sample/{new.filename}"))

train <- df %>% group_by(cultivar) %>% sample_n(15)
# file.copy(from = train$from.path, to = train$to.path)
```

Output a list of file paths. This can be used by FIJI in file > import > Stack From List... to make a virtual stack.  If you save it though, it saves as an actual (non-virtual) stack.

```{r}
write_csv(select(train, to.path), glue("{scandir}/Training Sample/file_list.csv"),col_names = FALSE)
```

