---
title: "2018 GCMS pre-treatment"
output: html_notebook
---
```{r}
library(tidyverse)
library(chemhelper)
library(here)
```

```{r}
Data.dir <- "/Volumes/as_rsch_orianslab_tea01$/IonAnalytics/IonAnalytics Projects/Shengzhou_2018/Data"

files <- dir(Data.dir,
             pattern = "Shengzhou_adj Integration Report.csv",
             full.names = TRUE, #adds full path
             recursive = TRUE) #drills down in directory structure

filenames <- str_extract(files, "(?<=/)[^/]+(?=/[^/]+$)")
# samples <- str_extract(filenames, "(?<=Hop_).+(?=\\.D)")
gc_tidy <- files %>%
  map(read_IA) %>%
  set_names(filenames) %>% 
  bind_rows(.id = "filename") %>% 
  rename(area = `Area [a.u.*s]`,
         rt = `R.Time [min.]`)
gc_tidy
```

```{r}
alkanes1 <- read_IA("/Volumes/as_rsch_orianslab_tea01$/IonAnalytics/IonAnalytics Projects/Shengzhou_2018/Data/073018_alkanemix/Meth_073018_alkanemix Integration Report.csv")
alkanes_lj <-
  alkanes1 %>% 
  slice(1:19) %>%  #that's enough I think.
  mutate(rt = ifelse(`R.Time [min.]` == 0, `Expect. [min.]`, `R.Time [min.]`)) %>% 
  select(Compound, rt) %>% 
  add_column(C_num = 6:24)


alkanes2 <- read_IA("/Volumes/as_rsch_orianslab_tea01$/IonAnalytics/IonAnalytics Projects/Shengzhou_2018/Data/082018_Alkane/Meth_073018_alkanemix Integration Report.csv")
alkanes_jgy <- 
  alkanes2 %>% 
  slice(1:19) %>% 
  mutate(rt = ifelse(`R.Time [min.]` == 0, `Expect. [min.]`, `R.Time [min.]`)) %>% 
  select(Compound, rt) %>% 
  add_column(C_num = 6:24)
```

```{r}
cresol311 <- as.cas("106445")
cresol416 <- as.cas("93516")
cedr <- as.cas(469614)
terp <- as.cas(562743)

cresol311.ri <- nist_ri(cresol311, "linear", "non-polar", "ramp") %>% 
  filter(gas == "Helium", str_detect(phase, "5"), thickness < 0.3) %>% 
  summarize(mean_ri = mean(RI))

cresol311.rt.lj <- calc_RT(1078.75, alkanes_lj$rt, alkanes_lj$C_num)
cresol311.rt.jgy <- calc_RT(1078.75, alkanes_jgy$rt, alkanes_jgy$C_num)



cresol416.ri <- nist_ri(cresol416, "linear", "non-polar", "custom") %>% 
  filter(gas == "Helium") %>% 
  summarize(mean_ri = mean(RI))

cresol416.rt.lj <- calc_RT(1193.025, alkanes_lj$rt, alkanes_lj$C_num)

cedr.ri <- nist_ri(cedr, 'linear', 'non-polar', 'ramp') %>% 
  filter(gas == "Helium", str_detect(phase, "5")) %>% 
  summarize(mean_ri = mean(RI))

calc_RT(cedr.ri$mean_ri[1], alkanes_jgy$rt, alkanes_jgy$C_num)

terp.ri <- nist_ri(terp, 'linear', 'non-polar', 'ramp') %>% 
  filter(gas == "Helium", str_detect(phase, "5")) %>% 
  summarize(mean_ri = mean(RI))
calc_RT(terp.ri$mean_ri[1], alkanes_lj$rt, alkanes_lj$C_num)
```

