---
title: "Geometrid Growth"
output: html_notebook
---
Wrangling and preliminary analysis for geometrid growth assay on manipulative leafhopper experiment conducted at TRI in Hangzhou.

```{r}
library(tidyverse)
library(here)
library(lubridate)
```
```{r}
geometrid <- read_csv(here("raw data", "Geometrid Feeding.csv"))
```
```{r}
plotdata <- geometrid %>% 
  gather(-Bags, -Treatment, key = date, value = weight) %>% 
  mutate(date = str_remove_all(date, "[a-z_\\(\\)]")) %>% 
  mutate(date = make_date(year = 2018, month = 8, day = str_match(date, "(?<=\\/)\\d+")))
```
```{r}
ggplot(plotdata, aes(x = date, y = weight, color = Treatment)) +
  stat_summary(geom = "pointrange", fun.data = mean_se) +
  stat_summary(geom = "line", fun.y = mean)
```
```{r}
geometrid %>% 
  mutate_if(is.double, funs(. - `weight_initial_(8/14)`)) %>% 
  ggplot(aes(x = Treatment, y = `weight_8/16`)) +
  geom_boxplot() +
  labs(x = "Leafhopper Treatment", y = "Weight Change (weight on Aug 16 - initial weight)")
```

